[pytest]
pythonpath = .
testpaths = tests
addopts = -v --html=reports/report.html --self-contained-html
markers =
    amazon: Amazon flow tests
    flipkart: Flipkart flow tests
    filling_form: Form filling tests
    instagram: Instagram flow tests
    youtube: YouTube search tests
    login: Login tests
    practice_window: Window handling tests
    practice_alert: Alert handling tests
