from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

def filling_form(driver):
    wait = WebDriverWait(driver, 40)
    driver.get("https://demoqa.com/automation-practice-form")
    first_name = wait.until(EC.element_to_be_clickable((By.ID,"firstName")))
    first_name.send_keys("Balaram")
    last_name = wait.until(EC.element_to_be_clickable((By.ID,"lastName")))
    last_name.send_keys("Tripathy")
    email = wait.until(EC.element_to_be_clickable((By.ID,"userEmail")))
    email.send_keys("balaramtripathy48@gmail.com")
    gender = wait.until(EC.element_to_be_clickable((By.XPATH,"//div[@class='form-check form-check-inline']")))
    gender.click()
    mobile_number = wait.until(EC.element_to_be_clickable((By.ID,"userNumber")))
    mobile_number.send_keys("6372043854")
    dropdown = wait.until(EC.element_to_be_clickable((By.ID,"dateOfBirthInput")))
    dropdown.click()
    dropdown_selector = Select(wait.until(EC.element_to_be_clickable((By.XPATH,"//select[@class='react-datepicker__month-select']"))))
    dropdown_selector.select_by_visible_text("December")
    dropdown_selector_1 = Select(wait.until(EC.visibility_of_element_located((By.XPATH,"//select[@class='react-datepicker__year-select']"))))
    dropdown_selector_1.select_by_visible_text("2002")
    date = wait.until(EC.element_to_be_clickable((By.XPATH,"//div[contains(@class,'react-datepicker__day react-datepicker__day--022')]")))
    date.click()
    subjects = wait.until(EC.element_to_be_clickable((By.ID,"subjectsInput")))
    subjects.send_keys("Maths")
    subjects.send_keys(Keys.ENTER)
    hobbies = wait.until(EC.element_to_be_clickable((By.ID,"hobbies-checkbox-1")))
    hobbies.click()
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    address = wait.until(EC.element_to_be_clickable((By.ID,"currentAddress")))
    address.send_keys("bramhana sahi,U.D.S pur")
    dropdown_1 = wait.until(EC.element_to_be_clickable((By.ID,"react-select-3-input")))
    dropdown_1.send_keys("NCR")
    dropdown_1.send_keys(Keys.ENTER)
    dropdown_2 = wait.until(EC.visibility_of_element_located((By.ID,"react-select-4-input")))
    dropdown_2.send_keys("Delhi")
    dropdown_2.send_keys(Keys.ENTER)
    submit = wait.until(EC.element_to_be_clickable((By.ID,"submit")))
    submit.click()
    final = wait.until(EC.element_to_be_clickable((By.ID,"closeLargeModal")))
    print("filling the form successfully")
    assert final.text == "Close","invalid text"

def filling_form_for_all(driver,name,last_name,email,gender,mobile_number,month,year,date,subjects,hobbies,address,state,city):
    driver.get("https://demoqa.com/automation-practice-form")
    wait = WebDriverWait(driver,10)
    nam = wait.until(EC.element_to_be_clickable((By.ID,"firstName")))
    nam.send_keys(name)
    titl = wait.until(EC.element_to_be_clickable((By.ID,"lastName")))
    titl.send_keys(last_name)
    emai = wait.until(EC.element_to_be_clickable((By.ID,"userEmail")))
    emai.send_keys(email)
    wait.until(EC.element_to_be_clickable((By.XPATH,f"//label[text()='{gender}']"))).click()
    numb = wait.until(EC.element_to_be_clickable((By.ID,"userNumber")))
    numb.send_keys(mobile_number)
    wait.until(EC.element_to_be_clickable((By.ID,"dateOfBirthInput"))).click()
    dropdown = Select(wait.until(EC.visibility_of_element_located((By.XPATH,"//select[@class='react-datepicker__month-select']"))))
    dropdown.select_by_visible_text(month)
    dropdown_1 = Select(wait.until((EC.visibility_of_element_located((By.XPATH,"//select[@class='react-datepicker__year-select']")))))
    dropdown_1.select_by_visible_text(year)
    date = wait.until(EC.visibility_of_element_located((By.XPATH,f"//div[contains(@class,'react-datepicker__day react-datepicker__day--022')]")))
    date.click()
    subject = wait.until(EC.element_to_be_clickable((By.ID,"subjectsInput")))
    subject.send_keys(subjects)
    subject.send_keys(Keys.ENTER)
    hobbies = wait.until(EC.element_to_be_clickable((By.XPATH,f"//label[text()='{hobbies}']")))
    hobbies.click()
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    addres = wait.until(EC.element_to_be_clickable((By.ID,"currentAddress")))
    addres.send_keys(address)
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    dropdown_1 = wait.until(EC.element_to_be_clickable((By.ID,"react-select-3-input")))
    dropdown_1.send_keys(state)
    dropdown_1.send_keys(Keys.ENTER)
    dropdown_2 = wait.until(EC.element_to_be_clickable((By.ID,"react-select-4-input")))
    dropdown_2.send_keys(city)
    dropdown_2.send_keys(Keys.ENTER)
    submit = wait.until(EC.element_to_be_clickable((By.ID, "submit")))
    driver.execute_script("arguments[0].scrollIntoView();", submit)
    # time.sleep(2)
    submit.click()
    # time.sleep(5)
    final = wait.until(EC.element_to_be_clickable((By.ID, "closeLargeModal")))
    print("filling the form successfully")
    assert final.text == "Close", "invalid text"